export const programingData=[
    'A.NET (A#/A sharp)',
    'A-0 System',
    'A+ ',
    'ABAP',
    'ABC',
    'ABC ALGOL',
    'ACC',
    'Accent',
    'Ace DASL',
    'Action!',
    'ActionScript',
    'Actor',
    'Ada',
    'Adenine (Haystack)',
    'AdvPL',
    'Agda',
    'Agilent VEE (Keysight VEE)',
    'Agora',
    'AIMMS',
    'Aldor',
    'Alef',
    'ALF',
    'ALGOL 58',
    'ALGOL 60',
    'ALGOL 68',
    'ALGOL W',
    'Alice',
    'Alma-0',
    'AmbientTalk',
    'Amiga E',
    'AMOS ',
    'AMPL',
    'Analitik',
    'AngelScript',
    'Apache Pig latin',
    'Apex',
    'APL',
    'AppleScript',
    'APT',
    'Arc',
    'ARexx',
    'Argus',
    'Assembly language',
    'AutoIt',
    'AutoLISP / Visual LISP',
    'Averest',
    'AWK',
    'Axum',
    'B',
    'Babbage',
    'Ballerina',
    'Bash',
    'BASIC',
    'Batch file' ,
    'bc',
    'BCPL',
    'BeanShell',
    'Bertrand',
    'BETA',
    'BLISS',
    'Blockly',
    'BlooP',
    'Boo',
    'Boomerang',
    'Bosque',
    'C',
    'C--',
    'C++',
    'C*',
    'C#',
    'C/AL',
    'Caché ObjectScript',
    'C Shell',
    'Caml',
    'Cayenne',
    'CDuce',
    'Cecil',
    'CESIL (Computer Education in Schools Instruction Language)',
    'Céu',
    'Ceylon',
    'CFEngine',
    'Cg (High-Level Shader/Shading Language [HLSL])',
    'Ch',
    'Chapel (Cascade High Productivity Language)',
    'Charm',
    'CHILL',
    'CHIP-8',
    'ChucK',
    'Cilk',
    'Control Language',
    'Claire',
    'Clarion',
    'Clean',
    'Clipper',
    'CLIPS',
    'CLIST',
    'Clojure',
    'CLU',
    'CMS-2',
    'COBOL',
    'CobolScript– COBOL Scripting language',
    'Cobra',
    'CoffeeScript',
    'ColdFusion',
    'COMAL',
    'COMIT',

]