export const softwareData = [
  'Photoshop',
  'Illustrator',
  'Acrobat Pro',
  'InDesign',
  'Premiere Pro',
  'After Effects',
  'Lightroom',
  'Premiere Rush',
  'Adobe XD',
  'Adobe Creative Cloud Express',
  'Adobe Animate',
  'Adobe Dreamweaver',
  'Adobe Stock',
  'Adobe Substance',
  'Adobe Audition',
  'Adobe Fonts',
  'Adobe Aero',
  'Adobe InCopy',
  'Adobe Document Cloud',
  'Adobe Experience Cloud',
  'Adobe Fresco',
  'Adobe Dimension',
  'Zmodeler',
  'ZBrush',
  'Wolfram Mathematica',
  'Wings 3D',
  'ViaCAD',
  'TrueSpace',
  'Tekla Structures',
  'Swift 3D',
  'Sweet Home 3D',
  'Strata 3D',
  'SpaceClaim',
  'SolidWorks',
  'solidThinking',
  'Solid Edge',
  'SketchUp',
  'Silo',
  'SharkCAD',
  'Shade 3D',
  'SelfCAD',
  'Seamless3d',
  'Sculptris',
  'ScanIP',
  'Rhinoceros 3D',
  'RFEM',
  'Remo 3D',
  'Realsoft 3D',
  'Quake Army Knife',
  'Promine',
  'Pro/ENGINEER',
  'PowerAnimator',
  'Poser',
  'OpenSCAD',
  'Open CASCADE',
  'Onshape',
  'Oculus Medium',
  'NX',
  'Nvil',
  'Modo',
  'Milkshape 3D',
  'MikuMikuDance',
  'MicroStation',
  'Metasequoia',
  'MASSIVE',
  'Makers Empire 3D',
  'LightWave 3D',
  'KeyCreator',
  'IRONCAD',
  'Houdini',
  'Hexagon',
  'Geomodeller3D',
  'FreeCAD',
  'Form-Z',
  'Flux',
  'Exa Corporation',
  'Electric Image Animation System',
  'DesignSpark Mechanical',
  'Daz Studio',
  'Clara.io',
  'CityEngine',
  'Cinema 4D',
  'Cheetah3D',
  'CATIA',
  'Carrara',
  'Bryce',
  'BRL-CAD',
  'BricsCAD',
  'Blender',
  'Bcad',
  'AutoQ3D Community',
  'AutoQ3D',
  'ArtMatic',
  'Art of Illusion',
  'ArchiCAD',
  'Animation:Master',
  'Anim8or',
  'Amapi',
  'Alibre Design',
  'Aladdin4D',
  'Adobe Dimension',
  'AC3D',
  '3DVIA Shape',
  '3D-Coat',
  '3D Slash',
  'AutoCAD',
  'AutoCAD Architecture',
  'AutoCAD Civil 3D',
  'AutoCAD Electrical',
  'AutoCAD Freestyle',
  'AutoCAD Inventor LT Suite',
  'AutoCAD Land',
  'AutoCAD LT',
  'AutoCAD Map 3D',
  'AutoCAD Mechanical',
  'AutoCAD MEP',
  'AutoCAD OEM',
  'AutoCAD P&ID',
  'AutoCAD Plant 3D',
  'AutoCAD Raster Design',
]
